language: php

php:
  # - '5.6'
    - '7.1'

sudo: false

before_script:
  - composer install 
  - npm install
  - php artisan key:generate
  - php artisan migrate --seed
  - cp .env.example .env

notifications:
  email:
    recipients:
      - himanshu-patel@live.com
      - support@agscybertech.com
    on_success: always
    on_failure: always